// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vacvbtvzwikwqbxshwdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhY3ZidHZ6d2lrd3FieHNod2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzAzMDMsImV4cCI6MjA2NzAwNjMwM30.4tkE-aWlZ3CxhTLE0EP5hztC_ZnGEIQvBZUM3oo3A5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});